services:
  - type: web
    name: separation-audio
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg libmp3lame-dev lame libsndfile1
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
